In [11]:
import cv2
import numpy as np

def detect_and_crop_object(image_path, template_path, scale_factor=1.2, min_size=50, max_size=400):
    # Load the main image and template image
    image = cv2.imread(image_path)
    template = cv2.imread(template_path, 0)  # Read the template as grayscale

    # Preprocess the template: Apply edge detection
    template_edges = cv2.Canny(template, 50, 150)

    # Convert the main image to grayscale
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Initialize the Generalized Hough Transform detector (Ballard)
    ght = cv2.createGeneralizedHoughBallard()
    ght.setTemplate(template_edges)

    # Perform edge detection on the main image
    edges = cv2.Canny(gray_image, 50, 150)

    # List to store detected objects
    detected_objects = []

    # Scale the template to different sizes
    h, w = template.shape
    for scale in np.arange(1.0, 2.0, 0.2):  # Try different scales
        resized_template = cv2.resize(template, (int(w * scale), int(h * scale)))
        resized_template_edges = cv2.Canny(resized_template, 50, 150)
        ght.setTemplate(resized_template_edges)
        
        # Detect objects with the current scaled template
        positions, _ = ght.detect(edges)

        # If at least one position is detected, we can crop the region
        if positions is not None and len(positions) > 0:
            print(f"Detected object at scale {scale}: {positions}")
            
            for detected_point in positions:
                x, y = int(detected_point[0][0]), int(detected_point[0][1])

                # Define the bounding box around the detected object
                h_resized, w_resized = resized_template.shape
                x1, y1 = int(x - w_resized / 2), int(y - h_resized / 2)
                x2, y2 = x1 + w_resized, y1 + h_resized

                # Ensure the coordinates are within the image bounds
                x1, y1 = max(0, x1), max(0, y1)
                x2, y2 = min(image.shape[1], x2), min(image.shape[0], y2)

                # Crop the detected object
                cropped_object = image[y1:y2, x1:x2]
                detected_objects.append(cropped_object)

                # Display the cropped object
                cv2.imshow(f"Detected Object at Scale {scale}", cropped_object)
                cv2.waitKey(0)

    cv2.destroyAllWindows()

    # If objects were detected, return them; otherwise, return None
    if detected_objects:
        # Save all cropped objects
        for i, obj in enumerate(detected_objects):
            cv2.imwrite(f'cropped_object_{i}.jpg', obj)
        return detected_objects
    else:
        print("No object detected.")
        return None

# Test the function with an image and template
image_path = '09 - e3del el soora ya3ammm.jpg'  # Path to the image with the object
template_path = 'cro2pped_image.jpg'  # Path to the template image (e.g., barcode template)
detect_and_crop_object(image_path, template_path)


Detected object at scale 1.0: [[[116.   0.   1.   0.]
  [156.   0.   1.   0.]
  [160.   0.   1.   0.]
  ...
  [ 80. 383.   1.   0.]
  [180. 383.   1.   0.]
  [220. 383.   1.   0.]]]
Detected object at scale 1.2: [[[ 91.   0.   1.   0.]
  [ 93.   0.   1.   0.]
  [ 96.   0.   1.   0.]
  ...
  [ 67. 397.   1.   0.]
  [101. 397.   1.   0.]
  [110. 400.   1.   0.]]]
Detected object at scale 1.4: [[[ 32.   0.   1.   0.]
  [ 34.   0.   1.   0.]
  [ 40.   0.   1.   0.]
  ...
  [ 96. 411.   1.   0.]
  [280. 411.   1.   0.]
  [ 84. 413.   1.   0.]]]
Detected object at scale 1.5999999999999999: [[[  1.   0.   1.   0.]
  [  5.   0.   1.   0.]
  [ 10.   0.   1.   0.]
  ...
  [  1. 431.   1.   0.]
  [  1. 433.   1.   0.]
  [ 20. 433.   1.   0.]]]
Detected object at scale 1.7999999999999998: [[[  2.   0.   1.   0.]
  [  6.   0.   1.   0.]
  [  8.   0.   1.   0.]
  ...
  [207. 441.   1.   0.]
  [207. 443.   1.   0.]
  [254. 445.   1.   0.]]]


[array([[[248, 248, 248],
         [248, 248, 248],
         [248, 248, 248],
         ...,
         [ 42,  42,  42],
         [130, 130, 130],
         [231, 231, 231]],
 
        [[248, 248, 248],
         [248, 248, 248],
         [248, 248, 248],
         ...,
         [ 21,  21,  21],
         [102, 102, 102],
         [202, 202, 202]],
 
        [[248, 248, 248],
         [248, 248, 248],
         [248, 248, 248],
         ...,
         [  0,   0,   0],
         [ 58,  58,  58],
         [153, 153, 153]],
 
        ...,
 
        [[248, 248, 248],
         [248, 248, 248],
         [248, 248, 248],
         ...,
         [  0,   0,   0],
         [ 21,  21,  21],
         [ 13,  13,  13]],
 
        [[248, 248, 248],
         [248, 248, 248],
         [248, 248, 248],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],
 
        [[248, 248, 248],
         [248, 248, 248],
         [248, 248, 248],
         ...,
         [ 90,  90,  90],
  